# @author Laurent Krishnathas
# @year 2018
version: '3.5'

services:
  traefik:
    deploy:
      resources:
        limits:
          memory: ${TRAEFIK_LIMIT_MEM}

  browser:
    image: browser:dotmatics-1.0
    volumes:
      - /efs/config/tmp/:/config:z
      - /efs/data/browser/WEB-INF/browser.properties:/config/browser.properties:z
      - /efs/data/browser/WEB-INF/dotmatics.license.txt:/config/dotmatics.license.txt:z
      - /efs/logs/browser:/usr/local/tomcat/logs:z
      - /efs/data/browser/tempfiles:/usr/local/tomcat/webapps/browser/tempfiles:z
      - /efs/data/browser/pdf:/usr/local/tomcat/webapps/browser/pdf:z
      - /efs/data/browser/profiles:/usr/local/tomcat/webapps/browser/images/profiles:z
      - '/efs/data/browser/raw data:/usr/local/tomcat/webapps/browser/raw data:z'

    deploy:
      resources:
        limits:
          memory: ${BROWSER_LIMIT_MEM}

  bioregister:
    image: bioregister:dotmatics-1.0
    volumes:
      - /efs/config/tmp:/config:z
      - /efs/data/bioregister.groovy:/config/bioregister.groovy:z
      - /efs/data/bioregister/c2c_attachments:/c2c_attachments:z
      - /efs/data/browser/WEB-INF/browser.properties:/config/browser.properties:z
      - /efs/data/browser/WEB-INF/dotmatics.license.txt:/config/dotmatics.license.txt:z
      - /efs/logs/bioregister:/usr/local/tomcat/logs:z
    deploy:
      resources:
        limits:
          memory: ${BIOREGISTER_LIMIT_MEM}
